insight/insight/config/urls.py
from django.contrib import admin
from django.urls import path, include
from insight.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
    path('test/', include('insight.urls')),
]

insight/insight/insight/urls.py
from django.urls import path

from . import views

app_name = 'insight'

urlpatterns = [
    path('', views.mbti_test, name='mbti_test'),
    path('ENFJ/', views.ENFJ, name='ENFJ'),
    path('ENFP/', views.ENFP, name='ENFP'),
    path('ENTJ/', views.ENTJ, name='ENTJ'),
    path('ENTP/', views.ENTP, name='ENTP'),
    path('ESFJ/', views.ESFJ, name='ESFJ'),
    path('ESFP/', views.ESFP, name='ESFP'),
    path('ESTJ/', views.ESTJ, name='ESTJ'),
    path('ESTP/', views.ESTP, name='ESTP'),
    path('INFJ/', views.INFJ, name='INFJ'),
    path('INFP/', views.INFP, name='INFP'),
    path('INTJ/', views.INTJ, name='INTJ'),
    path('INTP/', views.INTP, name='INTP'),
    path('ISFJ/', views.ISFJ, name='ISFJ'),
    path('ISFP/', views.ISFP, name='ISFP'),
    path('ISTJ/', views.ISTJ, name='ISTJ'),
    path('ISTP/', views.ISTP, name='ISTP'),
]

insight/insight/insight/models.py
from django.db import models

# Create your models here.

insight/insight/insight/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'start.html')

def mbti_test(request):
    return render(request, 'test.html')

def ENFJ(request):
    return render(request, 'result/ENFJ.html')

def ENFP(request):
    return render(request, 'result/ENFP.html')

def ENTJ(request):
    return render(request,'result/ENTJ.html')

def ENTP(request):
    return render(request, 'result/ENTP.html')

def ESFJ(request):
    return render(request, 'result/ESFJ.html')

def ESFP(request):
    return render(request, 'result/ESFP.html')

def ESTJ(request):
    return render(request, 'result/ESTJ.html')

def ESTP(request):
    return render(request, 'result/ESTP.html')

def INFJ(request):
    return render(request, 'result/INFJ.html')

def INFP(request):
    return render(request, 'result/INFP.html')

def INTJ(request):
    return render(request, 'result/INTJ.html')

def INTP(request):
    return render(request, 'result/INTP.html')

def ISFJ(request):
    return render(request, 'result/ISFJ.html')

def ISFP(request):
    return render(request, 'result/ISFP.html')

def ISTJ(request):
    return render(request, 'result/ISTJ.html')

def ISTP(request):
    return render(request, 'result/ISTP.html')

insight/insight/templates/insight/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HELLO</title>
</head>
<body>
    <h1>hi</h1>
</body>
</html>

insight/insight/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
 	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="shortcut icon" type="picture/png" href="{% static 'picture/보노보놐.png' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    {% block content %}
    <hr>
    <footer>
        ⓒ 2023 insight django project
    </footer>
    {% endblock %}
    {% block js %}
    <script  type="text/javascript" src="../static/test.js"></script>
    {% endblock %}
</body>
</html>

insight/insight/templates/mbti/test1.html
{% extends 'layout.html' %}
{% block content %}
<head>
    <title>1번 질문</title>
</head>
<body>
    <div class="shsd">
        <div class="shsdd">
            <div class="haeb">
                <div class="qud">수업이 끝났다 나의 행동은?</div>
            </div>
            <form method="post">
                <div class="qdsd">
                    <a href="{% url 'insight:second_question' %}">
                        <div class="answer">집 가서 쉬어야지..</div>
                    </a>
                    <br>
                    <a href="{% url 'insight:second_question' %}">
                        <div class="answer" style="margin-top: 20px;">수업 끝났다 술 묵자!!</div>
                    </a>
                </div>
            </form>
            <div class="row row-cols">
                <div class="d-flex justify-content-center">
                    1/12
                </div>
            </div>
        </div>
    </div>
    
</body>
{% endblock %}

insight/insight/templates/result/ENFJ.html
{% extends 'layout.html' %}
{% block content %}
<body class="content">
    <div class="start">
        <div class="mbti">
            <p>당신의 MBTI는</p>
            <p>ENFJ</p>
        </div>
        <div class="job">
            <p>변화를 좋아하는 당신!</p>
            <p>프론트엔드</p>
            <p>가 되어보는건 어떨까?</p>
        </div>
        <div class="character">
            <img src="/static/picture/front_developer.png" alt="캐릭터 일러스트">
        </div>
        <div class="caffein">
            <p>하루 평균 카페인 섭취량</p>
            <img src="/static/picture/COFFEE_rm.png" alt="커피 잔 수">
        </div>
        <div class="trend">
            <p>유행에 한창 민감할 나이</p>
            <img src="/static/picture/tumbler.png" alt="아이템 사진">  
        </div>
        <div class="traits">
            <p>특징</p>
            <ul>
                <li>사람들과 관계속에서 모두 조화롭게 잘 조율을 한다</li>
                <li>다른 사람들에게 무엇인가 도움을 주는것에 안달이 나있는 유형</li>
                <li>사람들이 무엇을 필요로 하고 무엇을 불편해 하는지 잘 파악한다</li>
                <li>사람들에게 관심이 많고 따듯한 사람들이지만 할말은 한다. &#40;적절한 타이밍에&#41;</li>
            </ul>
        </div>
        <div class="work">
            <p>하는 일</p>
            <ul>
                <li>백엔드 에서 가져온 데이터의 출력, 입력을 통한 로직 구성과 사용자 인터페이스에 대한 직업을 수행</li>
                <li>간단히 말해 User가 눈으로 보는 모든 것을 개발</li>
                <li>고객/사용자의 반응을 확인하여 즉각적으로 판단하고 빠르게 대응</li>
                <li>트렌드의 변화가 굉장히 빠르고 새로운 기술과 트렌드를 꾸준하게 파악해야한다</li>
            </ul>
        </div>
        <div class="skill">
            <p>필요 역량</p>
            <ul>
                <li>html, css, JavaScript, vue, python, React, npm</li>
                <li>UI, UX 경험</li>
                <li>디자인적 측면과 예술적인 부분 필요</li>
            </ul>
        </div>
    </div>
</body>
{% endblock %}

insight/insight/templates/result/ENFP.html
{% extends 'layout.html' %}
{% block content %}
<body class="content">
    <div class="start">
        <div class="mbti">
            <p>당신의 MBTI는</p>
            <p>ENFP</p>
        </div>
        <div class="job">
            <p>자유를 좋아하는 당신!</p>
            <p>AI 개발자</p>
            <p>가 되어보는건 어떨까?</p>
        </div>
        <div class="character">
            <img src="" alt="캐릭터 일러스트">
        </div>
        <div class="caffein">
            <p>하루 평균 카페인 섭취량</p>
            <img src="/static/picture/COFFEE_rm.png" alt="커피 잔 수">
            <img src="/static/picture/COFFEE_rm.png" alt="커피 잔 수">
        </div>
        <div class="trend">
            <p>유행에 한창 민감할 나이</p>
            <img src="" alt="아이템 사진">  
        </div>
        <div class="traits">
            <p>특징</p>
            <ul>
                <li>새로운 아이디어를 만들어 내고 가능성에서 에너지를 얻는다</li>
                <li>창의성과 직관적 통찰력으로 관습에서 벗어난 새로운 아이디어를 쉽게 생각 해 낸다</li>
                <li>불가능은 없다는 신념으로 새로운 가능성에 도전하는 것을 즐긴다</li>
                <li>사교적이고 활력이 넘치고 공감능력이 좋아서 새로운 사람들과도 잘 사귀는 편이다</li>
                <li>자신이 가지고 있는 아이디어를 다른 사람에게 좋은 영향력을 끼친다</li>
            </ul>
        </div>
        <div class="work">
            <p>하는 일</p>
            <ul>
                <li>기계 학습 모델과 알고리즘을 개발하고 훈련시키는 역할</li>
                <li>다양한 분야에서 AI를 개발하고 적용하기 위해 컴퓨터 프로그래밍
                    머신러닝, 딥러닝, 자연어 처리, 컴퓨터 비전 등 다양한 기술 지식 활용
                </li>
                <li>데이터 분석 및 처리, 모델링, 알고리즘 개발 을 수행 해 기존 시스템을 개선하거나 새로운 AI 시스템을 설계</li>
            </ul>
        </div>
        <div class="skill">
            <p>필요 역량</p>
            <ul>
                <li>Python, Java, C++, R</li>
                <li>수학 및 통계학 지식</li>
                <li>머신러닝, 딥러닝에 대한 이해</li>
            </ul>
        </div>
    </div>
</body>
{% endblock %}

insight/insight/templates/result/ENTJ.html
{% extends 'layout.html' %}
{% block content %}
<body class="content">
    <div class="start">
        <div class="mbti">
            <p>당신의 MBTI는</p>
            <p>ENTJ</p>
        </div>
        <div class="job">
            <p>계산을 좋아하는 당신!</p>
            <p>데이터 사이언스</p>
            <p>가 되어보는건 어떨까?</p>
        </div>
        <div class="character">
            <img src="" alt="캐릭터 일러스트">
        </div>
        <div class="caffein">
            <p>하루 평균 카페인 섭취량</p>
            <img src="/static/picture/COFFEE_rm.png" alt="커피 잔 수">
            <img src="/static/picture/COFFEE_rm.png" alt="커피 잔 수">
            <img src="/static/picture/COFFEE_rm.png" alt="커피 잔 수">
        </div>
        <div class="trend">
            <p>유행에 한창 민감할 나이</p>
            <img src="" alt="아이템 사진">  
        </div>
        <div class="traits">
            <p>특징</p>
            <ul>
                <li>카리스마 넘치는 리더형</li>
                <li>장기적인 안목을 토대로 큰 그림을 그리면서 이끌어가는 전력적 사령관의 모습</li>
                <li>타고난 지도자형 조직의 전체적인 구조와 운영원리를 통제하고 관리한다 틀에 벗어나는 행동은 싫어한다</li>
                <li>자신의 논리와 분석을 기반으로 모든것을 주도한다</li>
            </ul>
        </div>
        <div class="work">
            <p>하는 일</p>
            <ul>
                <li>데이터 분석, 통계, 기계학습, 예측 모델링, 데이터 시각화</li>
                <li>머신러닝을 이용해 미래 예측</li>
                <li>분석 뿐만 아니라 데이터 간 관계, 패턴, 규칙 등을 찾아내 모형화 후 머신러닝 서비스에 도입</li>
            </ul>
        </div>
        <div class="skill">
            <p>필요 역량</p>
            <ul>
                <li>Python, R, 수학 및 통계학</li>
                <li>머신러닝, 딥러닝, 빅데이터 처리기술</li>
                <li>비즈니스 이해력과 문제 해결 능력</li>
            </ul>
        </div>
    </div>
</body>
{% endblock %}

insight/insight/templates/result/ENTP.html
{% extends 'layout.html' %}
{% block content %}
<body class="content">
    <div class="start">
        <div class="mbti">
            <p>당신의 MBTI는</p>
            <p>ENTP</p>
        </div>
        <div class="job">
            <p>계산을 좋아하는 당신!</p>
            <p>임베디드 개발자</p>
            <p>가 되어보는건 어떨까?</p>
        </div>
        <div class="character">
            <img src="" alt="캐릭터 일러스트">
        </div>
        <div class="caffein">
            <p>하루 평균 카페인 섭취량</p>
            <img src="/static/picture/COFFEE_rm.png" alt="커피 잔 수">
            <img src="/static/picture/COFFEE_rm.png" alt="커피 잔 수">
            <img src="/static/picture/COFFEE_rm.png" alt="커피 잔 수">
        </div>
        <div class="trend">
            <p>유행에 한창 민감할 나이</p>
            <img src="" alt="아이템 사진">  
        </div>
        <div class="traits">
            <p>특징</p>
            <ul>
                <li>발명가형, 상상초월, 만능 아이디어맨</li>
                <li>풍부한 상상력을 바탕으로 새로운 것에 도전을 좋아한다</li>
                <li>가능성, 미래, 새로운 것에 항상 열린 사고로 접근해서 다방면에서 관심과 재능이 많다</li>
                <li>넓은 안목으로 흐름을 잘 파악하고 박힌 틀을 깨는 혁신적인 아이디어를 잘 만든다</li>
                <li>관심분야에 있어 매우 박식하고 새로운 도전이나 개발을 두려워 하지 않고 자신감이 넘친다</li>
            </ul>
        </div>
        <div class="work">
            <p>하는 일</p>
            <ul>
                <li>임베디드 및 펌웨어 프로그래머의 주요 업무는 하드웨어 제어 프로그램 및 특수목적의 응용프로그램을 개발한다</li>
                <li>임베디드 하드웨어 성능이 좋지 않기 때문에 프로그램 최적화를 주로 한다</li>
                <li>일반적으로 분석단계, 설계단계, 코딩단계, 시험단계의 절차를 거쳐 소프트웨어를 완성</li>
            </ul>
        </div>
        <div class="skill">
            <p>필요 역량</p>
            <ul>
                <li>C, C++, Python, JAVA</li>
                <li>하드웨어를 제어하는 Data Sheet등을 이해하고 응용하는 능력</li>
            </ul>
        </div>
    </div>
</body>
{% endblock %}

insight/insight/templates/result/ESFJ.html
{% extends 'layout.html' %}
{% block content %}
<body class="content">
    <div class="start">
        <div class="mbti">
            <p>당신의 MBTI는</p>
            <p>ESFJ</p>
        </div>
        <div class="job">
            <p>변화를 좋아하는 당신!</p>
            <p>모바일앱개발자</p>
            <p>가 되어보는건 어떨까?</p>
        </div>
        <div class="character">
            <img src="" alt="캐릭터 일러스트">
        </div>
        <div class="caffein">
            <p>하루 평균 카페인 섭취량</p>
            <img src="/static/picture/COFFEE_rm.png" alt="커피 잔 수">
        </div>
        <div class="trend">
            <p>유행에 한창 민감할 나이</p>
            <img src="" alt="아이템 사진">  
        </div>
        <div class="traits">
            <p>특징</p>
            <ul>
                <li>동정심이 많고 다른 사람에게 관심을 쏟으며 나눔과 베풂을 중시한다</li>
                <li>타고난 협력자로서 동료애가 많고 친절하며 능동적인 구성원이다</li>
                <li>반대 의견에 부딪혔을 때나, 자신의 요구가 거절당했을 때 마음의 상처를 받는다</li>
                <li>Give & Take가 확실하다</li>
            </ul>
        </div>
        <div class="work">
            <p>하는 일</p>
            <ul>
                <li>스마트폰이나 태블릿 PC등 모바일기기에서 사용되는 소프트웨어인 모바일 애플리케이션을 개발하고 수정하는 일을 한다</li>
                <li>국내외의 모바일 앱 개발 흐름 및 우리나라 사람들의 모바일기기 이용 특성에 적합한 애플리케이션을 기획하고 개발한다</li>
                <li>기업이나 기관이 이용하기 원하는 정보들을 체계적으로 모바일앱을 이용하여 관리할 수 있는 다양한 기능의 애플리케이션을 개발한다</li>
                <li>새로 개발하거나 이미 개발된 애플리케이션과 관리시스템 이용에 필요한 사용자 교육을 하거나 실제 모바일 앱운영에 필요한 시스템 구성과 관련된 내용을 고객과 회의를 통해 결정한다</li>
            </ul>
        </div>
        <div class="skill">
            <p>필요 역량</p>
            <ul>
                <li>Java, Kotlin</li>
                <li>안드로이드 프레임워크 이해하기</li>
            </ul>
        </div>
    </div>
</body>
{% endblock %}

insight/insight/templates/result/ESFP.html
{% extends 'layout.html' %}
{% block content %}
<body class="content">
    <div class="start">
        <div class="mbti">
            <p>당신의 MBTI는</p>
            <p>ESFP</p>
        </div>
        <div class="job">
            <p>게임을 좋아하는 당신!</p>
            <p>게임 개발자</p>
            <p>가 되어보는건 어떨까?</p>
        </div>
        <div class="character">
            <img src="" alt="캐릭터 일러스트">
        </div>
        <div class="caffein">
            <p>하루 평균 카페인 섭취량</p>
            <img src="/static/picture/COFFEE_rm.png" alt="커피 잔 수">
            <img src="/static/picture/COFFEE_rm.png" alt="커피 잔 수">
            <img src="/static/picture/COFFEE_rm.png" alt="커피 잔 수">
        </div>
        <div class="trend">
            <p>유행에 한창 민감할 나이</p>
            <img src="" alt="아이템 사진">  
        </div>
        <div class="traits">
            <p>특징</p>
            <ul>
                <li>사교적이고 활동적이며 수용력이 강하고 친절하며 낙천적이다</li>
                <li>주위의 사람이나 일어나는 일에 대하여 관심이 많으며 사람이나 사물을 다루는 사실적인 상식이 풍부하다</li>
                <li>어떤 조직체나 공동체에서 밝고 재미있는 분위기 조성 역할을 잘한다</li>
                <li>승부욕이 강하다</li>
            </ul>
        </div>
        <div class="work">
            <p>하는 일</p>
            <ul>
                <li>어떤 게임을 개발할 것인지 전체적인 기획을 하는 게임 기획자, 게임에 대한 것을 그림이나 그래픽으로 그려내고 구현하는 그래픽 디자이너</li>
                <li>게임의 기술적인 부분을 처리하고 기기에 맞게 구현하는 프로그래머</li>
                <li>기획자는 게임 준비부터 완성, 출시. 사후 관리까지 모든 기획을 하며, 컴퓨터 게임 개발 과정을 진두지휘 한다</li>
            </ul>
        </div>
        <div class="skill">
            <p>필요 역량</p>
            <ul>
                <li>C, C++, 어셈블리</li>
                <li>윈도우, 포토샵, 프리미어 등에 대한 지식 이해</li>
                <li>그래픽 애니메이션 개발자, 실무 경력이 있는 경력자</li>
            </ul>
        </div>
    </div>
</body>
{% endblock %}

insight/insight/templates/result/ESTJ.html
{% extends 'layout.html' %}
{% block content %}
<body class="content">
    <div class="start">
        <div class="mbti">
            <p>당신의 MBTI는</p>
            <p>ESTJ</p>
        </div>
        <div class="job">
            <p>자유를 좋아하는 당신!</p>
            <p>QA 개발자</p>
            <p>가 되어보는건 어떨까?</p>
        </div>
        <div class="character">
            <img src="" alt="캐릭터 일러스트">
        </div>
        <div class="caffein">
            <p>하루 평균 카페인 섭취량</p>
            <img src="/static/picture/COFFEE_rm.png" alt="커피 잔 수">
            <img src="/static/picture/COFFEE_rm.png" alt="커피 잔 수">
        </div>
        <div class="trend">
            <p>유행에 한창 민감할 나이</p>
            <img src="" alt="아이템 사진">  
        </div>
        <div class="traits">
            <p>특징</p>
            <ul>
                <li>현실적, 구체적, 사실적이며 어떠한 활동을 조직화하고 주도해 나가는 지도력이 있다</li>
                <li>실질적이고 현실 감각이 뛰어나며 일을 조직하고 계획하여 추진시키는 능력이 있다</li>
                <li>상대방의 디테일한 단점들을 보고 속에서 끓어오르는 열을 입 밖으로 토해내지 않는다</li>
                <li>외부에서의 모습과 내부에서의 모습이 완전 딴판이다</li>
            </ul>
        </div>
        <div class="work">
            <p>하는 일</p>
            <ul>
                <li>제품의 설계 및 생산과정 또는 고객의 요구사항이나 시장의 잠재수요 분석 등에 행해지는 여러 절차 과정을 정의하고 수립</li>
                <li>게임 기획단계부터 개발된 게임에 대해 테스트 계획을 세우고 개발이 완료되면 출시 전까지 다양한 환경에서 게임을 테스트해 보그가 없는지 체크</li>
                <li>프로젝트의 품질에 문제가 될 수 있는 모든 부분을 종합적으로 고려한다</li>
            </ul>
        </div>
        <div class="skill">
            <p>필요 역량</p>
            <ul>
                <li>istqb 자격증, 정보처리기사</li>
                <li>소프트웨어 공학 이해</li>
            </ul>
        </div>
    </div>
</body>
{% endblock %}

insight/insight/templates/result/ESTP.html
{% extends 'layout.html' %}
{% block content %}
<body class="content">
    <div class="start">
        <div class="mbti">
            <p>당신의 MBTI는</p>
            <p>ESTP</p>
        </div>
        <div class="job">
            <p>자유를 좋아하는 당신!</p>
            <p>IoT 개발자</p>
            <p>가 되어보는건 어떨까?</p>
        </div>
        <div class="character">
            <img src="" alt="캐릭터 일러스트">
        </div>
        <div class="caffein">
            <p>하루 평균 카페인 섭취량</p>
            <img src="/static/picture/COFFEE_rm.png" alt="커피 잔 수">
            <img src="/static/picture/COFFEE_rm.png" alt="커피 잔 수">
        </div>
        <div class="trend">
            <p>유행에 한창 민감할 나이</p>
            <img src="" alt="아이템 사진">  
        </div>
        <div class="traits">
            <p>특징</p>
            <ul>
                <li>클라우드 서비스를 활용하여 데이터를 저장하며, 사용자에게 원활한 애플리케이션을 제공한다</li>
                <li>데이터 베이스를 관리하고, 데이터를 찾아오거나 저장하며, 데이터가 안전하게 보관되도록 한다</li>
                <li>겸손하고 자만하지 않는 성격</li>
                <li>차분한 성격인 동시에 대인 관계 능력도 뛰어나다</li>
            </ul>
        </div>
        <div class="work">
            <p>하는 일</p>
            <ul>
                <li>센서와 스마트기기를 결합하여 개인에게 필요한 용도로 사용할 수 있도록 개발한다</li>
                <li>체중, 혈당, 혈압 등의 환자와 관련된 생체정보를 유무선 통신을 통해 스마트폰으로 전송할 수 있도록 하는 애플리케이션 개발을 한다</li>
                <li>USB, 블루투스, Wifi, NFC등의 네트워크를 활용하여 센서와 사물인터넷의 서비스 인터페이스 기술을 개발한다</li>
            </ul>
        </div>
        <div class="skill">
            <p>필요 역량</p>
            <ul>
                <li>C/C++, Python, Java 등 다양한 언어</li>
                <li>다양한 하드웨어 구성 요소를 이해</li>
                <li>데이터 흐름을 관리하고 분석하는 능력, 네트워크 프로토콜과 통신하는 방법 이해</li>
            </ul>
        </div>
    </div>
</body>
{% endblock %}

insight/insight/templates/result/INFJ.html
{% extends 'layout.html' %}
{% block content %}
<body class="content">
    <div class="start">
        <div class="mbti">
            <p>당신의 MBTI는</p>
            <p>INFJ</p>
        </div>
        <div class="job">
            <p>자유를 좋아하는 당신!</p>
            <p>풀스택형</p>
            <p>가 되어보는건 어떨까?</p>
        </div>
        <div class="character">
            <img src="" alt="캐릭터 일러스트">
        </div>
        <div class="caffein">
            <p>하루 평균 카페인 섭취량</p>
            <img src="/static/picture/COFFEE_rm.png" alt="커피 잔 수">
            <img src="/static/picture/COFFEE_rm.png" alt="커피 잔 수">
        </div>
        <div class="trend">
            <p>유행에 한창 민감할 나이</p>
            <img src="" alt="아이템 사진">  
        </div>
        <div class="traits">
            <p>특징</p>
            <ul>
                <li>호기심이 많고, 열정적이며 언제나 의문을 갖는다, 가슴 속에 묻어둔 질문들이 많다</li>
                <li>다른 사람의 감정을 그대로 흡수하기 때문에 공감 번아웃에 취약하다</li>
                <li>겉으로는 공감할 수 있지만, 속으로는 비판적으로 생각하는 경향이 있다</li>
                <li>자신의 능력과 지능에 대해 매우 자신감이 넘치며 자신에 대해 이야기하는 것을 좋아한다</li>
            </ul>
        </div>
        <div class="work">
            <p>하는 일</p>
            <ul>
                <li>프론트엔드부터 백엔드에 이르는 모든 소프트웨어 스택을 이해하는 개발자</li>
                <li>DB, Server, 시스템 엔지니어링 및 클라이언트의 모든 작업을 처리할 수 있는 엔지니어</li>
                <li>다양한 환경 및 플랫폼을 이해하고 사용되는 대부분의 언어와 지식을 갖춘 인재</li>
            </ul>
        </div>
        <div class="skill">
            <p>필요 역량</p>
            <ul>
                <li>Python, JavaScript, CSS, Node.js, Java</li>
                <li>웹 운영 자체의 이해도</li>
            </ul>
        </div>
    </div>
</body>
{% endblock %}

insight/insight/templates/start.html
{% extends 'layout.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'insight:mbti_test' %}">
        <div class="btn">시작하기</div>
    </a>
</body>
</html>


{% endblock %}